resources:
  - ../default
patches:
  - target:
      kind: Deployment
      name: mosaic-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: --leader-elect=false
